/*
 * Copyright (c) 2022 by the OnMetal authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package internal

import (
	"fmt"
	"sync"

	typed "sigs.k8s.io/structured-merge-diff/v4/typed"
)

func Parser() *typed.Parser {
	parserOnce.Do(func() {
		var err error
		parser, err = typed.NewParser(schemaYAML)
		if err != nil {
			panic(fmt.Sprintf("Failed to parse schema: %v", err))
		}
	})
	return parser
}

var parserOnce sync.Once
var parser *typed.Parser
var schemaYAML = typed.YAMLObject(`types:
- name: com.github.onmetal.onmetal-api.api.common.v1beta1.IP
  scalar: untyped
- name: com.github.onmetal.onmetal-api.api.common.v1beta1.IPPrefix
  scalar: untyped
- name: com.github.onmetal.onmetal-api.api.common.v1beta1.LocalUIDReference
  map:
    fields:
    - name: name
      type:
        scalar: string
      default: ""
    - name: uid
      type:
        scalar: string
      default: ""
    elementRelationship: atomic
- name: com.github.onmetal.onmetal-api.api.common.v1beta1.SecretKeySelector
  map:
    fields:
    - name: key
      type:
        scalar: string
    - name: name
      type:
        scalar: string
    elementRelationship: atomic
- name: com.github.onmetal.onmetal-api.api.common.v1beta1.Taint
  map:
    fields:
    - name: effect
      type:
        scalar: string
      default: ""
    - name: key
      type:
        scalar: string
      default: ""
    - name: value
      type:
        scalar: string
- name: com.github.onmetal.onmetal-api.api.common.v1beta1.Toleration
  map:
    fields:
    - name: effect
      type:
        scalar: string
    - name: key
      type:
        scalar: string
    - name: operator
      type:
        scalar: string
    - name: value
      type:
        scalar: string
- name: com.github.onmetal.onmetal-api.api.compute.v1beta1.DaemonEndpoint
  map:
    fields:
    - name: port
      type:
        scalar: numeric
      default: 0
- name: com.github.onmetal.onmetal-api.api.compute.v1beta1.EFIVar
  map:
    fields:
    - name: name
      type:
        scalar: string
      default: ""
    - name: uuid
      type:
        scalar: string
      default: ""
    - name: value
      type:
        scalar: string
      default: ""
- name: com.github.onmetal.onmetal-api.api.compute.v1beta1.EmptyDiskVolumeSource
  map:
    fields:
    - name: sizeLimit
      type:
        namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
- name: com.github.onmetal.onmetal-api.api.compute.v1beta1.EphemeralNetworkInterfaceSource
  map:
    fields:
    - name: networkInterfaceTemplate
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkInterfaceTemplateSpec
- name: com.github.onmetal.onmetal-api.api.compute.v1beta1.EphemeralVolumeSource
  map:
    fields:
    - name: volumeTemplate
      type:
        namedType: com.github.onmetal.onmetal-api.api.storage.v1beta1.VolumeTemplateSpec
- name: com.github.onmetal.onmetal-api.api.compute.v1beta1.Machine
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.onmetal.onmetal-api.api.compute.v1beta1.MachineSpec
      default: {}
    - name: status
      type:
        namedType: com.github.onmetal.onmetal-api.api.compute.v1beta1.MachineStatus
      default: {}
- name: com.github.onmetal.onmetal-api.api.compute.v1beta1.MachineClass
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: capabilities
      type:
        map:
          elementType:
            namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
- name: com.github.onmetal.onmetal-api.api.compute.v1beta1.MachinePool
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.onmetal.onmetal-api.api.compute.v1beta1.MachinePoolSpec
      default: {}
    - name: status
      type:
        namedType: com.github.onmetal.onmetal-api.api.compute.v1beta1.MachinePoolStatus
      default: {}
- name: com.github.onmetal.onmetal-api.api.compute.v1beta1.MachinePoolAddress
  map:
    fields:
    - name: address
      type:
        scalar: string
      default: ""
    - name: type
      type:
        scalar: string
      default: ""
- name: com.github.onmetal.onmetal-api.api.compute.v1beta1.MachinePoolCondition
  map:
    fields:
    - name: lastTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
      default: {}
    - name: message
      type:
        scalar: string
      default: ""
    - name: observedGeneration
      type:
        scalar: numeric
    - name: reason
      type:
        scalar: string
      default: ""
    - name: status
      type:
        scalar: string
      default: ""
    - name: type
      type:
        scalar: string
      default: ""
- name: com.github.onmetal.onmetal-api.api.compute.v1beta1.MachinePoolDaemonEndpoints
  map:
    fields:
    - name: machinepoolletEndpoint
      type:
        namedType: com.github.onmetal.onmetal-api.api.compute.v1beta1.DaemonEndpoint
      default: {}
- name: com.github.onmetal.onmetal-api.api.compute.v1beta1.MachinePoolSpec
  map:
    fields:
    - name: providerID
      type:
        scalar: string
      default: ""
    - name: taints
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.Taint
          elementRelationship: atomic
- name: com.github.onmetal.onmetal-api.api.compute.v1beta1.MachinePoolStatus
  map:
    fields:
    - name: addresses
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.compute.v1beta1.MachinePoolAddress
          elementRelationship: atomic
    - name: allocatable
      type:
        map:
          elementType:
            namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
    - name: availableMachineClasses
      type:
        list:
          elementType:
            namedType: io.k8s.api.core.v1.LocalObjectReference
          elementRelationship: atomic
    - name: capacity
      type:
        map:
          elementType:
            namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
    - name: conditions
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.compute.v1beta1.MachinePoolCondition
          elementRelationship: atomic
    - name: daemonEndpoints
      type:
        namedType: com.github.onmetal.onmetal-api.api.compute.v1beta1.MachinePoolDaemonEndpoints
      default: {}
    - name: state
      type:
        scalar: string
- name: com.github.onmetal.onmetal-api.api.compute.v1beta1.MachineSpec
  map:
    fields:
    - name: efiVars
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.compute.v1beta1.EFIVar
          elementRelationship: associative
          keys:
          - name
    - name: ignitionRef
      type:
        namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.SecretKeySelector
    - name: image
      type:
        scalar: string
    - name: imagePullSecret
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
    - name: machineClassRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
      default: {}
    - name: machinePoolRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
    - name: machinePoolSelector
      type:
        map:
          elementType:
            scalar: string
    - name: networkInterfaces
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.compute.v1beta1.NetworkInterface
          elementRelationship: associative
          keys:
          - name
    - name: power
      type:
        scalar: string
    - name: tolerations
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.Toleration
          elementRelationship: atomic
    - name: volumes
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.compute.v1beta1.Volume
          elementRelationship: associative
          keys:
          - name
- name: com.github.onmetal.onmetal-api.api.compute.v1beta1.MachineStatus
  map:
    fields:
    - name: machineID
      type:
        scalar: string
    - name: networkInterfaces
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.compute.v1beta1.NetworkInterfaceStatus
          elementRelationship: atomic
    - name: observedGeneration
      type:
        scalar: numeric
    - name: state
      type:
        scalar: string
    - name: volumes
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.compute.v1beta1.VolumeStatus
          elementRelationship: atomic
- name: com.github.onmetal.onmetal-api.api.compute.v1beta1.NetworkInterface
  map:
    fields:
    - name: ephemeral
      type:
        namedType: com.github.onmetal.onmetal-api.api.compute.v1beta1.EphemeralNetworkInterfaceSource
    - name: name
      type:
        scalar: string
      default: ""
    - name: networkInterfaceRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
- name: com.github.onmetal.onmetal-api.api.compute.v1beta1.NetworkInterfaceStatus
  map:
    fields:
    - name: handle
      type:
        scalar: string
    - name: ips
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.IP
          elementRelationship: atomic
    - name: lastStateTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: name
      type:
        scalar: string
      default: ""
    - name: state
      type:
        scalar: string
    - name: virtualIP
      type:
        namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.IP
- name: com.github.onmetal.onmetal-api.api.compute.v1beta1.Volume
  map:
    fields:
    - name: device
      type:
        scalar: string
    - name: emptyDisk
      type:
        namedType: com.github.onmetal.onmetal-api.api.compute.v1beta1.EmptyDiskVolumeSource
    - name: ephemeral
      type:
        namedType: com.github.onmetal.onmetal-api.api.compute.v1beta1.EphemeralVolumeSource
    - name: name
      type:
        scalar: string
      default: ""
    - name: volumeRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
- name: com.github.onmetal.onmetal-api.api.compute.v1beta1.VolumeStatus
  map:
    fields:
    - name: handle
      type:
        scalar: string
    - name: lastStateTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: name
      type:
        scalar: string
      default: ""
    - name: state
      type:
        scalar: string
- name: com.github.onmetal.onmetal-api.api.core.v1beta1.ObjectSelector
  map:
    fields:
    - name: kind
      type:
        scalar: string
      default: ""
    - name: matchExpressions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement
          elementRelationship: atomic
    - name: matchLabels
      type:
        map:
          elementType:
            scalar: string
- name: com.github.onmetal.onmetal-api.api.core.v1beta1.ResourceQuota
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.onmetal.onmetal-api.api.core.v1beta1.ResourceQuotaSpec
      default: {}
    - name: status
      type:
        namedType: com.github.onmetal.onmetal-api.api.core.v1beta1.ResourceQuotaStatus
      default: {}
- name: com.github.onmetal.onmetal-api.api.core.v1beta1.ResourceQuotaSpec
  map:
    fields:
    - name: hard
      type:
        map:
          elementType:
            namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
    - name: scopeSelector
      type:
        namedType: com.github.onmetal.onmetal-api.api.core.v1beta1.ResourceScopeSelector
- name: com.github.onmetal.onmetal-api.api.core.v1beta1.ResourceQuotaStatus
  map:
    fields:
    - name: hard
      type:
        map:
          elementType:
            namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
    - name: used
      type:
        map:
          elementType:
            namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
- name: com.github.onmetal.onmetal-api.api.core.v1beta1.ResourceScopeSelector
  map:
    fields:
    - name: matchExpressions
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.core.v1beta1.ResourceScopeSelectorRequirement
          elementRelationship: atomic
- name: com.github.onmetal.onmetal-api.api.core.v1beta1.ResourceScopeSelectorRequirement
  map:
    fields:
    - name: operator
      type:
        scalar: string
      default: ""
    - name: scopeName
      type:
        scalar: string
      default: ""
    - name: values
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
- name: com.github.onmetal.onmetal-api.api.ipam.v1beta1.Prefix
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.onmetal.onmetal-api.api.ipam.v1beta1.PrefixSpec
      default: {}
    - name: status
      type:
        namedType: com.github.onmetal.onmetal-api.api.ipam.v1beta1.PrefixStatus
      default: {}
- name: com.github.onmetal.onmetal-api.api.ipam.v1beta1.PrefixAllocation
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.onmetal.onmetal-api.api.ipam.v1beta1.PrefixAllocationSpec
      default: {}
    - name: status
      type:
        namedType: com.github.onmetal.onmetal-api.api.ipam.v1beta1.PrefixAllocationStatus
      default: {}
- name: com.github.onmetal.onmetal-api.api.ipam.v1beta1.PrefixAllocationSpec
  map:
    fields:
    - name: ipFamily
      type:
        scalar: string
    - name: prefix
      type:
        namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.IPPrefix
    - name: prefixLength
      type:
        scalar: numeric
    - name: prefixRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
    - name: prefixSelector
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector
- name: com.github.onmetal.onmetal-api.api.ipam.v1beta1.PrefixAllocationStatus
  map:
    fields:
    - name: lastPhaseTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: phase
      type:
        scalar: string
    - name: prefix
      type:
        namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.IPPrefix
- name: com.github.onmetal.onmetal-api.api.ipam.v1beta1.PrefixSpec
  map:
    fields:
    - name: ipFamily
      type:
        scalar: string
    - name: parentRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
    - name: parentSelector
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector
    - name: prefix
      type:
        namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.IPPrefix
    - name: prefixLength
      type:
        scalar: numeric
- name: com.github.onmetal.onmetal-api.api.ipam.v1beta1.PrefixStatus
  map:
    fields:
    - name: lastPhaseTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: phase
      type:
        scalar: string
    - name: used
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.IPPrefix
          elementRelationship: atomic
- name: com.github.onmetal.onmetal-api.api.ipam.v1beta1.PrefixTemplateSpec
  map:
    fields:
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.onmetal.onmetal-api.api.ipam.v1beta1.PrefixSpec
      default: {}
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.EphemeralPrefixSource
  map:
    fields:
    - name: prefixTemplate
      type:
        namedType: com.github.onmetal.onmetal-api.api.ipam.v1beta1.PrefixTemplateSpec
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.EphemeralVirtualIPSource
  map:
    fields:
    - name: virtualIPTemplate
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.VirtualIPTemplateSpec
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.IPBlock
  map:
    fields:
    - name: cidr
      type:
        namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.IPPrefix
      default: {}
    - name: except
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.IPPrefix
          elementRelationship: atomic
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.IPSource
  map:
    fields:
    - name: ephemeral
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.EphemeralPrefixSource
    - name: value
      type:
        namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.IP
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.LoadBalancer
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.LoadBalancerSpec
      default: {}
    - name: status
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.LoadBalancerStatus
      default: {}
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.LoadBalancerDestination
  map:
    fields:
    - name: ip
      type:
        namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.IP
      default: {}
    - name: targetRef
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.LoadBalancerTargetRef
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.LoadBalancerPort
  map:
    fields:
    - name: endPort
      type:
        scalar: numeric
    - name: port
      type:
        scalar: numeric
      default: 0
    - name: protocol
      type:
        scalar: string
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.LoadBalancerRouting
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: destinations
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.LoadBalancerDestination
          elementRelationship: atomic
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: networkRef
      type:
        namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.LocalUIDReference
      default: {}
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.LoadBalancerSpec
  map:
    fields:
    - name: ipFamilies
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: ips
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.IPSource
          elementRelationship: atomic
    - name: networkInterfaceSelector
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector
    - name: networkRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
      default: {}
    - name: ports
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.LoadBalancerPort
          elementRelationship: atomic
    - name: type
      type:
        scalar: string
      default: ""
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.LoadBalancerStatus
  map:
    fields:
    - name: ips
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.IP
          elementRelationship: atomic
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.LoadBalancerTargetRef
  map:
    fields:
    - name: name
      type:
        scalar: string
      default: ""
    - name: providerID
      type:
        scalar: string
      default: ""
    - name: uid
      type:
        scalar: string
      default: ""
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.NATGateway
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.NATGatewaySpec
      default: {}
    - name: status
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.NATGatewayStatus
      default: {}
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.NATGatewaySpec
  map:
    fields:
    - name: ipFamily
      type:
        scalar: string
      default: ""
    - name: networkRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
      default: {}
    - name: portsPerNetworkInterface
      type:
        scalar: numeric
    - name: type
      type:
        scalar: string
      default: ""
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.NATGatewayStatus
  map:
    fields:
    - name: ips
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.IP
          elementRelationship: atomic
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.Network
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkSpec
      default: {}
    - name: status
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkStatus
      default: {}
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkInterface
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkInterfaceSpec
      default: {}
    - name: status
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkInterfaceStatus
      default: {}
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkInterfaceSpec
  map:
    fields:
    - name: attributes
      type:
        map:
          elementType:
            scalar: string
    - name: ipFamilies
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
    - name: ips
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.IPSource
          elementRelationship: atomic
    - name: machineRef
      type:
        namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.LocalUIDReference
    - name: networkRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
      default: {}
    - name: prefixes
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.PrefixSource
          elementRelationship: atomic
    - name: providerID
      type:
        scalar: string
    - name: virtualIP
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.VirtualIPSource
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkInterfaceStatus
  map:
    fields:
    - name: ips
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.IP
          elementRelationship: atomic
    - name: lastStateTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: prefixes
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.IPPrefix
          elementRelationship: atomic
    - name: state
      type:
        scalar: string
    - name: virtualIP
      type:
        namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.IP
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkInterfaceTemplateSpec
  map:
    fields:
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkInterfaceSpec
      default: {}
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPeering
  map:
    fields:
    - name: name
      type:
        scalar: string
      default: ""
    - name: networkRef
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPeeringNetworkRef
      default: {}
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPeeringClaimRef
  map:
    fields:
    - name: name
      type:
        scalar: string
      default: ""
    - name: namespace
      type:
        scalar: string
    - name: uid
      type:
        scalar: string
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPeeringNetworkRef
  map:
    fields:
    - name: name
      type:
        scalar: string
      default: ""
    - name: namespace
      type:
        scalar: string
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPeeringStatus
  map:
    fields:
    - name: name
      type:
        scalar: string
      default: ""
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPolicy
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPolicySpec
      default: {}
    - name: status
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPolicyStatus
      default: {}
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPolicyCondition
  map:
    fields:
    - name: lastTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
      default: {}
    - name: message
      type:
        scalar: string
      default: ""
    - name: observedGeneration
      type:
        scalar: numeric
    - name: reason
      type:
        scalar: string
      default: ""
    - name: status
      type:
        scalar: string
      default: ""
    - name: type
      type:
        scalar: string
      default: ""
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPolicyEgressRule
  map:
    fields:
    - name: ports
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPolicyPort
          elementRelationship: atomic
    - name: to
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPolicyPeer
          elementRelationship: atomic
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPolicyIngressRule
  map:
    fields:
    - name: from
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPolicyPeer
          elementRelationship: atomic
    - name: ports
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPolicyPort
          elementRelationship: atomic
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPolicyPeer
  map:
    fields:
    - name: ipBlock
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.IPBlock
    - name: objectSelector
      type:
        namedType: com.github.onmetal.onmetal-api.api.core.v1beta1.ObjectSelector
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPolicyPort
  map:
    fields:
    - name: endPort
      type:
        scalar: numeric
    - name: port
      type:
        scalar: numeric
    - name: protocol
      type:
        scalar: string
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPolicySpec
  map:
    fields:
    - name: egress
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPolicyEgressRule
          elementRelationship: atomic
    - name: ingress
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPolicyIngressRule
          elementRelationship: atomic
    - name: networkInterfaceSelector
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector
      default: {}
    - name: networkRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
      default: {}
    - name: policyTypes
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPolicyStatus
  map:
    fields:
    - name: conditions
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPolicyCondition
          elementRelationship: atomic
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkSpec
  map:
    fields:
    - name: incomingPeerings
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPeeringClaimRef
          elementRelationship: associative
          keys:
          - name
    - name: peerings
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPeering
          elementRelationship: associative
          keys:
          - name
    - name: providerID
      type:
        scalar: string
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkStatus
  map:
    fields:
    - name: peerings
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.NetworkPeeringStatus
          elementRelationship: associative
          keys:
          - name
    - name: state
      type:
        scalar: string
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.PrefixSource
  map:
    fields:
    - name: ephemeral
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.EphemeralPrefixSource
    - name: value
      type:
        namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.IPPrefix
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.VirtualIP
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.VirtualIPSpec
      default: {}
    - name: status
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.VirtualIPStatus
      default: {}
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.VirtualIPSource
  map:
    fields:
    - name: ephemeral
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.EphemeralVirtualIPSource
    - name: virtualIPRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.VirtualIPSpec
  map:
    fields:
    - name: ipFamily
      type:
        scalar: string
      default: ""
    - name: targetRef
      type:
        namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.LocalUIDReference
    - name: type
      type:
        scalar: string
      default: ""
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.VirtualIPStatus
  map:
    fields:
    - name: ip
      type:
        namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.IP
- name: com.github.onmetal.onmetal-api.api.networking.v1beta1.VirtualIPTemplateSpec
  map:
    fields:
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.onmetal.onmetal-api.api.networking.v1beta1.VirtualIPSpec
      default: {}
- name: com.github.onmetal.onmetal-api.api.storage.v1beta1.Bucket
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.onmetal.onmetal-api.api.storage.v1beta1.BucketSpec
      default: {}
    - name: status
      type:
        namedType: com.github.onmetal.onmetal-api.api.storage.v1beta1.BucketStatus
      default: {}
- name: com.github.onmetal.onmetal-api.api.storage.v1beta1.BucketAccess
  map:
    fields:
    - name: endpoint
      type:
        scalar: string
      default: ""
    - name: secretRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
- name: com.github.onmetal.onmetal-api.api.storage.v1beta1.BucketClass
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: capabilities
      type:
        map:
          elementType:
            namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
- name: com.github.onmetal.onmetal-api.api.storage.v1beta1.BucketCondition
  map:
    fields:
    - name: lastTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
      default: {}
    - name: message
      type:
        scalar: string
    - name: observedGeneration
      type:
        scalar: numeric
    - name: reason
      type:
        scalar: string
    - name: status
      type:
        scalar: string
      default: ""
    - name: type
      type:
        scalar: string
      default: ""
- name: com.github.onmetal.onmetal-api.api.storage.v1beta1.BucketPool
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.onmetal.onmetal-api.api.storage.v1beta1.BucketPoolSpec
      default: {}
    - name: status
      type:
        namedType: com.github.onmetal.onmetal-api.api.storage.v1beta1.BucketPoolStatus
      default: {}
- name: com.github.onmetal.onmetal-api.api.storage.v1beta1.BucketPoolSpec
  map:
    fields:
    - name: providerID
      type:
        scalar: string
      default: ""
    - name: taints
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.Taint
          elementRelationship: atomic
- name: com.github.onmetal.onmetal-api.api.storage.v1beta1.BucketPoolStatus
  map:
    fields:
    - name: availableBucketClasses
      type:
        list:
          elementType:
            namedType: io.k8s.api.core.v1.LocalObjectReference
          elementRelationship: atomic
    - name: state
      type:
        scalar: string
- name: com.github.onmetal.onmetal-api.api.storage.v1beta1.BucketSpec
  map:
    fields:
    - name: bucketClassRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
    - name: bucketPoolRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
    - name: bucketPoolSelector
      type:
        map:
          elementType:
            scalar: string
    - name: tolerations
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.Toleration
          elementRelationship: atomic
- name: com.github.onmetal.onmetal-api.api.storage.v1beta1.BucketStatus
  map:
    fields:
    - name: access
      type:
        namedType: com.github.onmetal.onmetal-api.api.storage.v1beta1.BucketAccess
    - name: conditions
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.storage.v1beta1.BucketCondition
          elementRelationship: atomic
    - name: lastStateTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: state
      type:
        scalar: string
- name: com.github.onmetal.onmetal-api.api.storage.v1beta1.Volume
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.onmetal.onmetal-api.api.storage.v1beta1.VolumeSpec
      default: {}
    - name: status
      type:
        namedType: com.github.onmetal.onmetal-api.api.storage.v1beta1.VolumeStatus
      default: {}
- name: com.github.onmetal.onmetal-api.api.storage.v1beta1.VolumeAccess
  map:
    fields:
    - name: driver
      type:
        scalar: string
      default: ""
    - name: handle
      type:
        scalar: string
      default: ""
    - name: secretRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
    - name: volumeAttributes
      type:
        map:
          elementType:
            scalar: string
- name: com.github.onmetal.onmetal-api.api.storage.v1beta1.VolumeClass
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: capabilities
      type:
        map:
          elementType:
            namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: resizePolicy
      type:
        scalar: string
- name: com.github.onmetal.onmetal-api.api.storage.v1beta1.VolumeCondition
  map:
    fields:
    - name: lastTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
      default: {}
    - name: message
      type:
        scalar: string
    - name: observedGeneration
      type:
        scalar: numeric
    - name: reason
      type:
        scalar: string
    - name: status
      type:
        scalar: string
      default: ""
    - name: type
      type:
        scalar: string
      default: ""
- name: com.github.onmetal.onmetal-api.api.storage.v1beta1.VolumeEncryption
  map:
    fields:
    - name: secretRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
      default: {}
- name: com.github.onmetal.onmetal-api.api.storage.v1beta1.VolumePool
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: kind
      type:
        scalar: string
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.onmetal.onmetal-api.api.storage.v1beta1.VolumePoolSpec
      default: {}
    - name: status
      type:
        namedType: com.github.onmetal.onmetal-api.api.storage.v1beta1.VolumePoolStatus
      default: {}
- name: com.github.onmetal.onmetal-api.api.storage.v1beta1.VolumePoolCondition
  map:
    fields:
    - name: lastTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
      default: {}
    - name: message
      type:
        scalar: string
      default: ""
    - name: observedGeneration
      type:
        scalar: numeric
    - name: reason
      type:
        scalar: string
      default: ""
    - name: status
      type:
        scalar: string
      default: ""
    - name: type
      type:
        scalar: string
      default: ""
- name: com.github.onmetal.onmetal-api.api.storage.v1beta1.VolumePoolSpec
  map:
    fields:
    - name: providerID
      type:
        scalar: string
      default: ""
    - name: taints
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.Taint
          elementRelationship: atomic
- name: com.github.onmetal.onmetal-api.api.storage.v1beta1.VolumePoolStatus
  map:
    fields:
    - name: allocatable
      type:
        map:
          elementType:
            namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
    - name: availableVolumeClasses
      type:
        list:
          elementType:
            namedType: io.k8s.api.core.v1.LocalObjectReference
          elementRelationship: atomic
    - name: capacity
      type:
        map:
          elementType:
            namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
    - name: conditions
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.storage.v1beta1.VolumePoolCondition
          elementRelationship: atomic
    - name: state
      type:
        scalar: string
- name: com.github.onmetal.onmetal-api.api.storage.v1beta1.VolumeSpec
  map:
    fields:
    - name: claimRef
      type:
        namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.LocalUIDReference
    - name: encryption
      type:
        namedType: com.github.onmetal.onmetal-api.api.storage.v1beta1.VolumeEncryption
    - name: image
      type:
        scalar: string
    - name: imagePullSecretRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
    - name: resources
      type:
        map:
          elementType:
            namedType: io.k8s.apimachinery.pkg.api.resource.Quantity
    - name: tolerations
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.common.v1beta1.Toleration
          elementRelationship: atomic
    - name: unclaimable
      type:
        scalar: boolean
    - name: volumeClassRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
    - name: volumePoolRef
      type:
        namedType: io.k8s.api.core.v1.LocalObjectReference
    - name: volumePoolSelector
      type:
        map:
          elementType:
            scalar: string
- name: com.github.onmetal.onmetal-api.api.storage.v1beta1.VolumeStatus
  map:
    fields:
    - name: access
      type:
        namedType: com.github.onmetal.onmetal-api.api.storage.v1beta1.VolumeAccess
    - name: conditions
      type:
        list:
          elementType:
            namedType: com.github.onmetal.onmetal-api.api.storage.v1beta1.VolumeCondition
          elementRelationship: atomic
    - name: lastStateTransitionTime
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: state
      type:
        scalar: string
- name: com.github.onmetal.onmetal-api.api.storage.v1beta1.VolumeTemplateSpec
  map:
    fields:
    - name: metadata
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
      default: {}
    - name: spec
      type:
        namedType: com.github.onmetal.onmetal-api.api.storage.v1beta1.VolumeSpec
      default: {}
- name: io.k8s.api.core.v1.LocalObjectReference
  map:
    fields:
    - name: name
      type:
        scalar: string
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.api.resource.Quantity
  scalar: untyped
- name: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
  map:
    elementType:
      scalar: untyped
      list:
        elementType:
          namedType: __untyped_atomic_
        elementRelationship: atomic
      map:
        elementType:
          namedType: __untyped_deduced_
        elementRelationship: separable
- name: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector
  map:
    fields:
    - name: matchExpressions
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement
          elementRelationship: atomic
    - name: matchLabels
      type:
        map:
          elementType:
            scalar: string
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement
  map:
    fields:
    - name: key
      type:
        scalar: string
      default: ""
    - name: operator
      type:
        scalar: string
      default: ""
    - name: values
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
    - name: fieldsType
      type:
        scalar: string
    - name: fieldsV1
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1
    - name: manager
      type:
        scalar: string
    - name: operation
      type:
        scalar: string
    - name: subresource
      type:
        scalar: string
    - name: time
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
- name: io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
  map:
    fields:
    - name: annotations
      type:
        map:
          elementType:
            scalar: string
    - name: creationTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
      default: {}
    - name: deletionGracePeriodSeconds
      type:
        scalar: numeric
    - name: deletionTimestamp
      type:
        namedType: io.k8s.apimachinery.pkg.apis.meta.v1.Time
    - name: finalizers
      type:
        list:
          elementType:
            scalar: string
          elementRelationship: associative
    - name: generateName
      type:
        scalar: string
    - name: generation
      type:
        scalar: numeric
    - name: labels
      type:
        map:
          elementType:
            scalar: string
    - name: managedFields
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
          elementRelationship: atomic
    - name: name
      type:
        scalar: string
    - name: namespace
      type:
        scalar: string
    - name: ownerReferences
      type:
        list:
          elementType:
            namedType: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
          elementRelationship: associative
          keys:
          - uid
    - name: resourceVersion
      type:
        scalar: string
    - name: selfLink
      type:
        scalar: string
    - name: uid
      type:
        scalar: string
- name: io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference
  map:
    fields:
    - name: apiVersion
      type:
        scalar: string
      default: ""
    - name: blockOwnerDeletion
      type:
        scalar: boolean
    - name: controller
      type:
        scalar: boolean
    - name: kind
      type:
        scalar: string
      default: ""
    - name: name
      type:
        scalar: string
      default: ""
    - name: uid
      type:
        scalar: string
      default: ""
    elementRelationship: atomic
- name: io.k8s.apimachinery.pkg.apis.meta.v1.Time
  scalar: untyped
- name: __untyped_atomic_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
- name: __untyped_deduced_
  scalar: untyped
  list:
    elementType:
      namedType: __untyped_atomic_
    elementRelationship: atomic
  map:
    elementType:
      namedType: __untyped_deduced_
    elementRelationship: separable
`)
