apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  namespace: onmetal-system
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: control-plane
                      operator: In
                      values:
                        - apiserver
                topologyKey: topology.kubernetes.io/zone
      securityContext:
        runAsNonRoot: false
      containers:
        - name: apiserver
          args:
            - --etcd-cafile=/etc/kubernetes/pki/etcd/server-ca.crt
            - --etcd-certfile=/etc/kubernetes/pki/etcd/server-client.crt
            - --etcd-keyfile=/etc/kubernetes/pki/etcd/server-client.key
            - --etcd-servers=https://localhost:2379
            - --secure-port=9443
            - --audit-log-path=-
            - --feature-gates=APIPriorityAndFairness=false
            - --audit-log-maxage=0
            - --audit-log-maxbackup=0
            - --tls-cert-file=/tmp/k8s-apiserver/serving-certs/tls.crt
            - --tls-private-key-file=/tmp/k8s-apiserver/serving-certs/tls.key
          ports:
            - name: apiserver
              $patch: delete
            - containerPort: 9443
              name: apiserver
              protocol: TCP
          securityContext:
            runAsUser: 0
          readinessProbe:
            httpGet:
              path: /readyz
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
          volumeMounts:
            - mountPath: /etc/kubernetes/pki
              name: k8s-certs
              readOnly: true
      # By using this, we make sure we end up on the same node as the etcd.
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: k8s-certs
          hostPath:
            path: /media/data/k3s/server/tls
            type: Directory
