/*
 * Copyright (c) 2022 by the OnMetal authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/onmetal/onmetal-api/client-go/onmetalapi/typed/storage/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeStorageV1beta1 struct {
	*testing.Fake
}

func (c *FakeStorageV1beta1) Buckets(namespace string) v1beta1.BucketInterface {
	return &FakeBuckets{c, namespace}
}

func (c *FakeStorageV1beta1) BucketClasses() v1beta1.BucketClassInterface {
	return &FakeBucketClasses{c}
}

func (c *FakeStorageV1beta1) BucketPools() v1beta1.BucketPoolInterface {
	return &FakeBucketPools{c}
}

func (c *FakeStorageV1beta1) Volumes(namespace string) v1beta1.VolumeInterface {
	return &FakeVolumes{c, namespace}
}

func (c *FakeStorageV1beta1) VolumeClasses() v1beta1.VolumeClassInterface {
	return &FakeVolumeClasses{c}
}

func (c *FakeStorageV1beta1) VolumePools() v1beta1.VolumePoolInterface {
	return &FakeVolumePools{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeStorageV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
